
version: "3"
services: 
  nextjs:
      build:
        context: .
        dockerfile: ./nextjs/Dockerfile
      volumes:
        - ./src:/app
      ports:
        - "3000:3000"
      command: "sh -c 'yarn && yarn dev'"

