# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Prometheus-001
    orgId: 1
  - name: Prometheus-002
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: Prometheus
    # <string, required> datasource type. Required
    type: prometheus
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    url: nginx/prometheus/
  - name: Prometheus-001
    type: prometheus
    orgId: 1
    url: prometheus-001:9090
  - name: Prometheus-002
    type: prometheus
    orgId: 1
    url: prometheus-002:9090
  - name: TargetNode-101
    type: node_exporter:9100
    orgId: 1

